#*** Example Identity Main Policy
#*** Written in YAML
#
tc_rules:
    # Traffic Classification Rulesets and Rules
    tc_ruleset_1:
        - comment: OpenFlow Protocol Traffic
          match_type: any
          conditions_list:
              - match_type: any
                tcp_src: 6633
                tcp_dst: 6633
          actions:
              set_qos_tag: QoS_treatment=system_priority
              set_desc_tag: description="OpenFlow Protocol Traffic"
        - comment: Basic Statistical Classifier
          match_type: any
          conditions_list:
              - match_type: any
                # statistical_qos_bandwidth_1: off
                statistical_voip_p2p: on
          actions: 
              pass_return_tags: true
#
identity:
    # Control how identity information is collected
    # This is a 1 for on and 0 for off but will later tie to set of
    # ports on which to run it
    #
    # Turn this on to collect ARP MAC address to IPv4 address mappings:
    arp: 0
    #
    # Turn this on to collect Link Layer Discovery Protocol information:
    lldp: 0
    #
    # Turn this on to collect DNS reply data matching services to IP addresses:
    dns: 0
    #
    # Turn this on to collect DHCP information about address allocations and
    # hostnames:
    dhcp: 0
